import { async } from '@firebase/util';
import Head from 'next/head';
import Image from 'next/image';
import { getProviders, getSession, useSession } from "next-auth/react";

import Feed from '../components/Feed';
import Sidebar from '../components/Sidebar';
import Login from '../components/Login';
import CommentModal from '../components/CommentModal';
import Widgets from '../components/Widgets';

import styles from '../styles/Home.module.css';
import { useRecoilState } from 'recoil';
import { modalState, postIdState } from "../atoms/modalAtom";
import { IFollowResult, IProvider, ITrendingResult } from '../model/Model';

interface HomePageProps {
  trendingResults: ITrendingResult[];
  followResults: IFollowResult[];
  providers: IProvider[];
}

export default function Home({ trendingResults, followResults, providers }: HomePageProps) {
  const { data: session } = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState);
  if (!session)
    return <Login providers={providers} />;

  return (
    <div className=''>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black min-h-screen flex max-w-[1500px] mx-auto'>
        <Sidebar />
        <Feed />
        {/* {session.user.name} */}
        <Widgets trendingResults={trendingResults} followResults={followResults} />
        {isOpen && <CommentModal />}
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const trendingResults = await fetch("https://jsonkeeper.com/b/NKEV").then(
    (res) => res.json()
  );
  const followResults = await fetch("https://jsonkeeper.com/b/WWMJ").then(
    (res) => res.json()
  );
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      session,
    },
  };
}